### PR TITLE
CHANGE delta time

### PR DESCRIPTION
**Pull request by StephanMeijer**

### CODE REVIEW

**Comment by pylint** [comment]
**pylint results:**

```
************* Module nbp.io.input_providers.calculation_input_provider
C:  7, 0: Line too long (147/100) (line-too-long)
C:  8, 0: Line too long (195/100) (line-too-long)
C: 14, 0: Line too long (106/100) (line-too-long)
C: 15, 0: Line too long (113/100) (line-too-long)
C: 16, 0: Line too long (114/100) (line-too-long)
C: 17, 0: Line too long (107/100) (line-too-long)
C: 18, 0: Line too long (115/100) (line-too-long)
C: 20, 0: Line too long (116/100) (line-too-long)
C: 24, 0: Line too long (106/100) (line-too-long)
C: 25, 0: Line too long (115/100) (line-too-long)
C: 26, 0: Line too long (114/100) (line-too-long)
C: 27, 0: Line too long (107/100) (line-too-long)
C: 28, 0: Line too long (115/100) (line-too-long)
C: 30, 0: Line too long (116/100) (line-too-long)
C: 34, 0: Line too long (119/100) (line-too-long)
C: 35, 0: Line too long (114/100) (line-too-long)
C: 36, 0: Line too long (107/100) (line-too-long)
C: 37, 0: Line too long (115/100) (line-too-long)
C: 39, 0: Line too long (116/100) (line-too-long)
C: 59, 0: Line too long (106/100) (line-too-long)
C: 60, 0: Line too long (113/100) (line-too-long)
C: 61, 0: Line too long (114/100) (line-too-long)
C: 62, 0: Line too long (107/100) (line-too-long)
C: 63, 0: Line too long (115/100) (line-too-long)
C: 65, 0: Line too long (116/100) (line-too-long)
C: 95, 0: Trailing whitespace (trailing-whitespace)
C: 99, 0: Line too long (319/100) (line-too-long)
C:159, 0: Trailing whitespace (trailing-whitespace)
C:162, 0: Line too long (118/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
C:  3, 0: Missing class docstring (missing-docstring)
C: 91, 4: Missing method docstring (missing-docstring)
************* Module nbp.io.input_providers.input_provider
C:  1, 0: Missing module docstring (missing-docstring)
C:  3, 0: Missing class docstring (missing-docstring)
R:  3, 0: Too few public methods (1/2) (too-few-public-methods)
************* Module nbp.io.input_providers.file_input_provider
C:  1, 0: Missing module docstring (missing-docstring)
W:  4, 0: Method 'get_bodies' is abstract in class 'InputProvider' but is not overridden (abstract-method)
************* Module nbp.io.input_providers.start_value_input_providers.csv_start_value_input_provider
C:  1, 0: Missing module docstring (missing-docstring)
C:  4, 0: Missing class docstring (missing-docstring)
W: 12,19: Used builtin function 'filter'. Using a list comprehension can be clearer. (bad-builtin)
W: 14,16: Used builtin function 'map'. Using a list comprehension can be clearer. (bad-builtin)
R: 35, 4: Method could be a function (no-self-use)
R: 38, 4: Method could be a function (no-self-use)
R: 44, 4: Method could be a function (no-self-use)
************* Module nbp.bodies.body
C: 26, 0: Line too long (110/100) (line-too-long)
C: 31, 0: Line too long (110/100) (line-too-long)
C: 44, 0: Line too long (109/100) (line-too-long)
C:  1, 0: Missing module docstring (missing-docstring)
E:  1, 0: Unable to import 'numpy' (import-error)
C:  3, 0: Missing class docstring (missing-docstring)
R:  3, 0: Too few public methods (0/2) (too-few-public-methods)
E:  6, 0: class already defined line 3 (function-redefined)
C:  6, 0: Missing class docstring (missing-docstring)
R:  7, 4: Too many arguments (6/5) (too-many-arguments)


Report
======
120 statements analysed.

Statistics by type
------------------

+---------+-------+-----------+-----------+------------+---------+
|type     |number |old number |difference |%documented |%badname |
+=========+=======+===========+===========+============+=========+
|module   |11     |5          |+6.00      |54.55       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|class    |6      |3          |+3.00      |16.67       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|method   |19     |12         |+7.00      |94.74       |0.00     |
+---------+-------+-----------+-----------+------------+---------+
|function |0      |0          |=          |0           |0        |
+---------+-------+-----------+-----------+------------+---------+



External dependencies
---------------------
::

    nbp 
      \-bodies (nbp.io.input_providers.calculation_input_provider)
      | \-body (nbp.io.input_providers.start_value_input_providers.csv_start_value_input_provider)
      \-io 
        \-input_providers 
          \-file_input_provider (nbp.io.input_providers.start_value_input_providers.csv_start_value_input_provider)
          \-input_provider (nbp.io.input_providers.file_input_provider)



Raw metrics
-----------

+----------+-------+------+---------+-----------+
|type      |number |%     |previous |difference |
+==========+=======+======+=========+===========+
|code      |162    |37.33 |92       |+70.00     |
+----------+-------+------+---------+-----------+
|docstring |215    |49.54 |199      |+16.00     |
+----------+-------+------+---------+-----------+
|comment   |2      |0.46  |2        |=          |
+----------+-------+------+---------+-----------+
|empty     |55     |12.67 |33       |+22.00     |
+----------+-------+------+---------+-----------+



Duplication
-----------

+-------------------------+------+---------+-----------+
|                         |now   |previous |difference |
+=========================+======+=========+===========+
|nb duplicated lines      |0     |0        |=          |
+-------------------------+------+---------+-----------+
|percent duplicated lines |0.000 |0.000    |=          |
+-------------------------+------+---------+-----------+



Messages by category
--------------------

+-----------+-------+---------+-----------+
|type       |number |previous |difference |
+===========+=======+=========+===========+
|convention |43     |38       |+5.00      |
+-----------+-------+---------+-----------+
|refactor   |6      |2        |+4.00      |
+-----------+-------+---------+-----------+
|warning    |3      |0        |+3.00      |
+-----------+-------+---------+-----------+
|error      |2      |2        |=          |
+-----------+-------+---------+-----------+



% errors / warnings by module
-----------------------------

+----------------------------------------------------------------------------------+-------+--------+---------+-----------+
|module                                                                            |error  |warning |refactor |convention |
+==================================================================================+=======+========+=========+===========+
|nbp.bodies.body                                                                   |100.00 |0.00    |33.33    |13.95      |
+----------------------------------------------------------------------------------+-------+--------+---------+-----------+
|nbp.io.input_providers.start_value_input_providers.csv_start_value_input_provider |0.00   |66.67   |50.00    |4.65       |
+----------------------------------------------------------------------------------+-------+--------+---------+-----------+
|nbp.io.input_providers.file_input_provider                                        |0.00   |33.33   |0.00     |2.33       |
+----------------------------------------------------------------------------------+-------+--------+---------+-----------+
|nbp.io.input_providers.input_provider                                             |0.00   |0.00    |16.67    |4.65       |
+----------------------------------------------------------------------------------+-------+--------+---------+-----------+
|nbp.io.input_providers.calculation_input_provider                                 |0.00   |0.00    |0.00     |74.42      |
+----------------------------------------------------------------------------------+-------+--------+---------+-----------+



Messages
--------

+-----------------------+------------+
|message id             |occurrences |
+=======================+============+
|line-too-long          |30          |
+-----------------------+------------+
|missing-docstring      |11          |
+-----------------------+------------+
|no-self-use            |3           |
+-----------------------+------------+
|trailing-whitespace    |2           |
+-----------------------+------------+
|too-few-public-methods |2           |
+-----------------------+------------+
|bad-builtin            |2           |
+-----------------------+------------+
|too-many-arguments     |1           |
+-----------------------+------------+
|import-error           |1           |
+-----------------------+------------+
|function-redefined     |1           |
+-----------------------+------------+
|abstract-method        |1           |
+-----------------------+------------+



Global evaluation
-----------------
Your code has been rated at 4.83/10 (previous run: 3.42/10, +1.41)


```

**Comment by highlow9** [comment]
Now let's wait for the test to see if my patch can get us up to 100% coverage! :D

**Comment by StephanMeijer** [comment]
No, we won't get 100% converage. I pushed some code in last night, which is not tested at all.

**Comment by highlow9** [comment]
Why did you push code that is not tested?

**Comment by StephanMeijer** [comment]
Because working TDD is not a habit of mine yet.

We'll test it as soon as we use it.

**Pull request merged**
