### PR TITLE
Added doctest

### PR DESCRIPTION
**Pull request by highlow9**
Added doctest and fixed one_tick and fixed minimal distance

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Travis tells us there's one test failing.

**Comment by highlow9** [comment]
This error is ocuring because the other pull request I did wasn't yet merged while the test ran. And that pull request contrained bug fixes.

**Comment by StephanMeijer** [comment]
Can you pull from our repositiory and fix the doctest?

**Comment by highlow9** [comment]
The test should rerun now.

**Comment by highlow9** [comment]
Once you have merged this I will add coverage of change delta time.

**Comment by StephanMeijer** [comment]
Made an error in the commit-message. Referenced #22 instead of #18.

**Pull request merged**
