### PR TITLE
Improved/added doctests

### PR DESCRIPTION
**Pull request by highlow9**

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Thanks for the contribution. Did you run the tests?

**Comment by highlow9** [comment]
Jup

**Comment by StephanMeijer** [comment]
Are you sure? 
A function returning value: 

```
1kg.velocity = array([[ 0.0 ],
                           [ -19.63929948],
                            [ 0.0 ]])
```

Seems incorrect to me. Seems like assigning a value to a variable.

**Comment by highlow9** [comment]
Oops forgot a =.

**Comment by StephanMeijer** [comment]
Yeah, and a `True`.

**Comment by StephanMeijer** [comment]
(and `>>>`)

**Pull request closed without merging**
