### PR TITLE
fixed doctest 'acceleration_to_one'

### PR DESCRIPTION
**Pull request by highlow9**

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Did you run the tests? Did they succeed?

**Comment by highlow9** [comment]
It one change to the outcome of an existing doctest so it works now. Did you even look at the change?

**Comment by StephanMeijer** [comment]
Closing this pull request makes it impossible to pull. 
I want to make sure you executed the tests. Last time you thought your tests were working, but they were not.

**Comment by highlow9** [comment]
I forked the project will continu working there including this one char change.

**Comment by StephanMeijer** [comment]
You could open this pull request and do another pull request when your new work is done.

**Pull request closed without merging**
