### PR TITLE
Changed distance_to

### PR DESCRIPTION
**Pull request by highlow9**
Deleted if statement because it had no use.

### CODE REVIEW

**Comment by StephanMeijer** [comment]
Dear Tim,

Please, write a doctest for this function. Create a new body, and run distance_to on itself. Make sure it returns a Numpy-array containing 3 zeroes.

**Comment by highlow9** [comment]
I removed the if statement because it was useless so that function doesn't need to be tested anymore. It will still give 0,0,0 if you do it with the same body.

**Comment by StephanMeijer** [comment]
Please, write a test for that.

**Comment by highlow9** [comment]
That test would be useless but because you seem to want to have a second test....

**Comment by StephanMeijer** [comment]
It won't be useless. It would be a good description of the behavior of the function.

**Comment by highlow9** [comment]
Added the useless test

**Comment by StephanMeijer** [comment]
I think it's irrational to think that test is useless. .It describes the function perfectly

**Comment by Ghostbird** [comment]
Ah, I saw that weirdness in the code. And I wondered why it wasn't removed. Good call. Also, I agree with Stephan, testing a self difference is a very important test case. You don't want to end up with stuff like body1.distanceTo(body1) = (0.1e-17, 0.1e-17, 0.1e-17) due to float rounding errors etcetera.

**Comment by highlow9** [comment]
Yeah that is true and the test indeed doesn't hurt. But I removed the if because first of all it would never be used and second of all because when it would be used and it gave such an error it wound't be a significant problem.

**Comment by StephanMeijer** [comment]
One of the tests are failing on Travis. We should take a look.

**Comment by StephanMeijer** [comment]
Function `absolute_distance_to_one` is failing.

```
    def absolute_distance_to_one(self, other: Body) -> numpy.ndarray:
        """Takes two instances of a bodies and calculates the absolute distance.
        >>> earth = Body("Earth", 5.972*(10**24), 100.0, (1.496*(10**11), 0, 0), (0, 29290, 0))
        >>> moon = Body("Moon", 0.0735*(10**24), 100.0, (1.496*(10**11), 384.4*(10**6), 0), (1050, 29290, 0))
        >>> moon.absolute_distance_to_one(earth)
        384400000.0
        """
        return numpy.linalg.norm(test)
```

Please replace `return numpy.linalg.norm(test)` with `return numpy.linalg.norm(other.position - self.position)`

**Comment by highlow9** [comment]
Fixed it. The variable 'test' that Stephan wanted to remove was removed but i forgot to readd the calculation that test was given.

**Comment by StephanMeijer** [comment]
Great! All tests are passing!

**Pull request merged**
